### ISSUE TITLE
Failure on msvc-12.0

### ISSUE THREAD

**Issue by pdimov** [boostorg/fusion#159]
```
#include <boost/fusion/container/vector.hpp>
#include <boost/type.hpp>

int main()
{
	boost::fusion::vector<int, float> v1, v2;
	v1 = v2;
}
```

```
c:\projects\testbed2013\testbed.cpp(7): error C2036: 'boost::type' : unknown size
```

This comes up in the Spirit tests, f.ex. here:

https://ci.appveyor.com/project/boostorg/boost/build/1.0.4754-develop/job/yy8ymq7qvy73ce3c

**Comment by Flast** [comment]
It might be caused by #154, I'll investigate.

**Comment by Kojoley** [comment]
It is not #154 if it is not on the master. Look for Spirits `qi_debug-p3`, `qi_pass_container2-p3`, `qi_pass_container2-p3` fails on MSVC 10, 11, 12.

**Comment by Flast** [comment]
#154 is already merged into master. Isn't spirit master still old?

**Comment by Kojoley** [comment]
> #154 is already merged into master.

I see... GitHub shows only `develop` in branch list for the commit, I fooled by it the second time in the last weeks.

> Isn't spirit master still old?

Yes, it is.
